# Generated by Django 4.1.1 on 2022-09-23 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitee',
            name='status',
            field=models.CharField(choices=[('CR', 'Current'), ('PS', 'Past')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='commitee',
            name='updatedBy',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 8, 48, 713542)),
        ),
        migrations.AddField(
            model_name='project',
            name='updatedBy',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 8, 48, 713191)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 8, 48, 713521)),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 8, 48, 713145)),
        ),
    ]
