# Generated by Django 4.1.1 on 2022-09-23 20:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_commitee_member_alter_commitee_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 48, 16, 928323)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 48, 16, 928342)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 48, 16, 927954)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 48, 16, 928000)),
        ),
    ]
