# Generated by Django 4.1.1 on 2022-09-26 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_commitee_startdate_alter_commitee_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 387244)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 387263)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 386736)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 386776)),
        ),
        migrations.CreateModel(
            name='Minute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendees', models.CharField(max_length=500)),
                ('discussion', models.CharField(max_length=2000)),
                ('resolution', models.CharField(max_length=1000)),
                ('todos', models.CharField(max_length=1000)),
                ('date', models.DateField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 387541))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
