# Generated by Django 4.1.1 on 2022-09-26 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_commitee_startdate_alter_commitee_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 291609)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 291628)),
        ),
        migrations.AlterField(
            model_name='minute',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 291892)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 291131)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 291175)),
        ),
    ]
