# Generated by Django 4.1.1 on 2022-09-26 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_project_prjtype_alter_commitee_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 460568)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 460589)),
        ),
        migrations.AlterField(
            model_name='minute',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 460860)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 460057)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 460100)),
        ),
    ]
