# Generated by Django 4.1.1 on 2022-09-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_commitee_startdate_alter_commitee_updatedon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitee',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 212857)),
        ),
        migrations.AlterField(
            model_name='commitee',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 212876)),
        ),
        migrations.AlterField(
            model_name='minute',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 213145)),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 212358)),
        ),
        migrations.AlterField(
            model_name='project',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 212401)),
        ),
    ]
