# Generated by Django 4.1.1 on 2022-09-23 20:27

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_commitee_startdate_remove_commitee_updatedby_and_more'),
        ('batchfund', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='project',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 27, 13, 790802)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 27, 13, 790813)),
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contributionhist',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='contributionhist',
            name='updatedBy',
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 27, 13, 792040)),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ManyToManyField(to='accounts.project'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributionhist',
            name='contribution',
            field=models.ManyToManyField(to='batchfund.contribution'),
        ),
        migrations.AddField(
            model_name='contributionhist',
            name='updatedBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
