# Generated by Django 4.1.1 on 2022-09-23 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_commitee_member_alter_commitee_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batchfund', '0002_remove_contribution_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='project',
        ),
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 23, 20, 44, 35, 742853)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 44, 35, 742865)),
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='contributionhist',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='contributionhist',
            name='updatedBy',
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 23, 20, 44, 35, 743119)),
        ),
        migrations.AddField(
            model_name='contribution',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.project', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionhist',
            name='contribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='batchfund.contribution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contributionhist',
            name='updatedBy',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
    ]
