# Generated by Django 4.1.1 on 2022-09-24 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchfund', '0004_alter_contribution_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 24, 0, 23, 26, 77659)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 0, 23, 26, 77670)),
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 0, 23, 26, 77914)),
        ),
    ]
