# Generated by Django 4.1.1 on 2022-09-24 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchfund', '0005_alter_contribution_startdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='period',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='status',
        ),
        migrations.AddField(
            model_name='contribution',
            name='currency',
            field=models.CharField(choices=[('RS', 'Rs'), ('CAD', 'C$'), ('USD', 'US$'), ('SGD', 'SG$'), ('GBP', 'GBP'), ('AUD', 'AU$')], default='RS', max_length=3),
        ),
        migrations.AddField(
            model_name='contributionhist',
            name='status',
            field=models.CharField(choices=[('CMTD', 'Committed'), ('TRFD', 'Transfered')], default='CMTD', max_length=4),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.IntegerField(max_length=9),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 24, 22, 46, 53, 65558)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 22, 46, 53, 65568)),
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 24, 22, 46, 53, 65811)),
        ),
    ]
