# Generated by Django 4.1.1 on 2022-09-26 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchfund', '0007_alter_contribution_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 388099)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 388110)),
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 388393)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distrDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 389156)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 389184)),
        ),
        migrations.AlterField(
            model_name='distributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 389449)),
        ),
    ]
