# Generated by Django 4.1.1 on 2022-09-26 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchfund', '0008_alter_contribution_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 292411)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 292422)),
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 292664)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distrDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 293323)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 293348)),
        ),
        migrations.AlterField(
            model_name='distributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 15, 22, 45, 293592)),
        ),
    ]
