# Generated by Django 4.1.1 on 2022-09-27 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batchfund', '0011_alter_contribution_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 213653)),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 213664)),
        ),
        migrations.AlterField(
            model_name='contributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 213918)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='distrDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 214586)),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 214612)),
        ),
        migrations.AlterField(
            model_name='distributionhist',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 214859)),
        ),
    ]
