# Generated by Django 4.1.1 on 2022-09-26 14:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_commitee_startdate_alter_commitee_updatedon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=2000)),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 391908))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('reviewedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='videow/%Y')),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 392425))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='paddyprj.projectupdate')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txType', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdraw'), ('INCOME', 'Interest')], max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(max_length=9)),
                ('date', models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 391573))),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 391587))),
                ('exType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddyprj.expensetype')),
                ('txOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txOwner', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='photos/%Y')),
                ('figNo', models.IntegerField(default=0)),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='photos/%Y')),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 392148))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='paddyprj.projectupdate')),
                ('updatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(max_length=9)),
                ('startDate', models.DateField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 391323))),
                ('endDate', models.DateField(blank=True, null=True)),
                ('updatedOn', models.DateTimeField(default=datetime.datetime(2022, 9, 26, 14, 59, 38, 391334))),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
