# Generated by Django 4.1.1 on 2022-09-26 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_commitee_startdate_alter_commitee_updatedon_and_more'),
        ('paddyprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 463728)),
        ),
        migrations.AlterField(
            model_name='investor',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 463738)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 464516)),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 464288)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 464020)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 464036)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 26, 21, 34, 52, 464779)),
        ),
        migrations.CreateModel(
            name='PaddyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costPerShare', models.DecimalField(decimal_places=2, max_digits=9)),
                ('totalShares', models.IntegerField()),
                ('landArea', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costPrep', models.IntegerField()),
                ('costSeed', models.IntegerField()),
                ('costFertilizer', models.IntegerField(null=True)),
                ('costHarvest', models.IntegerField()),
                ('costStorage', models.IntegerField(null=True)),
                ('estHarvest', models.IntegerField(null=True)),
                ('estSalePrice', models.IntegerField(null=True)),
                ('contract', models.CharField(max_length=2000, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.project')),
            ],
        ),
        migrations.AlterField(
            model_name='investor',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddyprj.paddyproject'),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paddyprj.paddyproject'),
        ),
    ]
