# Generated by Django 4.1.1 on 2022-09-27 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paddyprj', '0002_alter_investor_enddate_alter_investor_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='paddyprj.paddyproject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investor',
            name='startDate',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 215838)),
        ),
        migrations.AlterField(
            model_name='investor',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 215848)),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='costHarvest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='costPerShare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='costPrep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='costSeed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='landArea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='paddyproject',
            name='totalShares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 216645)),
        ),
        migrations.AlterField(
            model_name='projectupdate',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 216415)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 216138)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 216151)),
        ),
        migrations.AlterField(
            model_name='video',
            name='updatedOn',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 14, 58, 51, 216922)),
        ),
    ]
